# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/handlename/ssmwrap
    environment:
      - GO111MODULE: 'on'
      - TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          key: go-packages-{{ checksum "go.sum" }}
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: run test
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v . | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
      - save_cache:
          key: go-packages-{{ checksum "go.sum" }}
          paths:
            - vendor
  upload:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/handlename/ssmwrap
    environment:
      - GO111MODULE: 'on'
    steps:
      - checkout
      - restore_cache:
          key: go-packages-{{ checksum "go.sum" }}
      - run: go get github.com/Songmu/goxz/cmd/goxz
      - run: go get github.com/tcnksm/ghr
      - run: make upload
      - save_cache:
          key: go-packages-{{ checksum "go.sum" }}
          paths:
            - vendor

workflows:
  version: 2
  test:
    jobs:
      - test

  upload:
    jobs:
      - upload:
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /v[0-9]+\.[0-9]+\.[0-9]+/
