# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/handlename/ssmwrap
    steps:
      - checkout
      - restore_cache:
          key: go-packages-{{ checksum "Gopkg.lock" }}
      - run: dep ensure
      - run: go test -v .
      - save_cache:
          key: go-packages-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

workflows:
  version: 2
  test:
    jobs:
      - test
