name: go
on: [push]
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.14
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go
      - uses: actions/checkout@v2
      - name: build & test
        run: |
          go test -v .
